version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: yarn start
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test