version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: yarn start
workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - test
        requires:
          - install